version: "3.8"

services:

  instrument_service:
    build: ./instrument_service
    container_name: instrument_service
    ports:
      - "8000:8000"
    depends_on:
      - market_data_service
    environment:
      DOWNLOAD_SERVICE: http://market_data_service:8000/download-tickers/
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  market_data_service:
    build: ./market_download_service
    container_name: market_data_service
    depends_on:
      - data_storage_service
    environment:
      DOWNLOAD_START_DATE: None
      DOWNLOAD_END_DATE: None
      DOWNLOAD_PERIOD: '5y'
      DOWNLOAD_INTERVAL: '1d'
      STORAGE_SERVICE_URL: http://data_storage_service:8000/data/bulk
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  data_storage_service:
    build: ./data_storage_service
    container_name: data_storage_service
    depends_on:
      - db
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
