version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bullcapital
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network # Assign to network
    # Add healthcheck so auth-service can wait for it
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bullcapital"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Banco de dados específico para o ai-service
  ai-postgres:
    image: postgres:15
    container_name: ai_service_postgres
    environment:
      POSTGRES_DB: ai_service_db
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password_2025
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - ai_postgres_data:/var/lib/postgresql/data
    networks:
      - dev-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_user -d ai_service_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
      # --- Database Connection Env Vars ---
      - USER=postgres
      - PASSWORD=postgres
      - HOST=db                     # Service name of the Postgres container
      - PORT=5432                   # Standard Postgres port
      - DBNAME=bullcapital
      - USE_SSL=false               # Disable SSL for local Postgres connection
      # --- JWT & App Settings ---
      # Replace 'your-super-secret-jwt-key-change-in-prod' with a strong secret key,
      # especially for production.
      - SECRET_KEY=your-super-secret-jwt-key-change-in-prod
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - DEBUG_SQL=false
      # Ensure these origins match where your frontend is running
      - ALLOWED_ORIGINS=["http://localhost:3000","http://localhost:8000","http://localhost:5173"]
    restart: unless-stopped
    # Use the correct module path for your FastAPI app
    # Adjust 'app.app:app' if your main file or app instance is named differently
    # Using 'sh -c' is fine, but direct command is often cleaner if no complex shell logic is needed.
    command: uvicorn app:app --host 0.0.0.0 --port 8003 --reload
    depends_on:
      db:
        # Wait for the database to be ready (requires healthcheck on db service)
        condition: service_healthy
    networks:
      - dev-network # Assign to network

  market-data-service:
    build:
      context: ./market-data-service
    container_name: market-data-service
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
      # Add other necessary env vars for market-data-service if needed
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload
    networks:
      - dev-network # Assign to network

  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - user=ai_user
      - password=ai_password_2025
      - host=ai-postgres
      - port=5432
      - dbname=ai_service_db
      - openai_api_key=${OPENAI_API_KEY}
    restart: unless-stopped
    command: python3 -m app.main
    depends_on:
      ai-postgres:
        condition: service_healthy
    networks:
      - dev-network
  
  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      # Tell the gateway where the auth service is located within the Docker network
      - AUTH_SERVICE_URL=http://auth-service:8003
      # Add other necessary env vars for gateway-service if needed (e.g., MARKET_DATA_SERVICE_URL)
      - MARKET_DATA_SERVICE_URL=http://market-data-service:8002
      - AI_SERVICE_URL=http://ai-service:8001
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - auth-service
      - market-data-service
      - ai-service
    networks:
      - dev-network # Assign to network

  frontend-web:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - dev-network

  # PgAdmin unificado para ambos os bancos de dados
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: bullcapital_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bullcapital.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dev-network
    restart: unless-stopped
    depends_on:
      - db
      - ai-postgres

volumes:
  pgdata:
  ai_postgres_data:
  pgadmin_data:

networks:
  dev-network:
    driver: bridge