version: '3.12'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bullcapital
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - dev-network


  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"
    depends_on:
      - db

  market-data-service:
    build:
      context: ./market-data-service
    container_name: market-data-service
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"


  ai-service:
    build:
      context: ./ai-service
    container_name: ai-service
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - user=postgres
      - password=postgres
      - host=db
      - port=5432
      - dbname=bullcapital
    restart: unless-stopped
    command: python3 -m app.main
    depends_on:
      - db
    networks:
      - dev-network



  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - auth-service
      - market-data-service

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bullcapital.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db
    networks:
      - dev-network

volumes:
  pgdata:

networks:
  dev-network:
    driver: bridge