version: '3.12'

services:
  db:
    image: postgres:14
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bullcapital
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "8003:8003"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload"
    depends_on:
      - db

  data-storage-service:
    build:
      context: ./data-storage-service
    container_name: data-storage-service
    ports:
      - "8004:8004"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8004 --reload"
    depends_on:
      - db

  instrument-service:
    build:
      context: ./instrument-service
    container_name: instrument-service
    ports:
      - "8005:8005"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8005 --reload"
    depends_on:
      - db

  market-data-service:
    build:
      context: ./market-data-service
    container_name: market-data-service
    ports:
      - "8002:8002"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"


  market-download-service:
    build:
      context: ./market-download-service
    container_name: market-download-service
    ports:
      - "8007:8007"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8007 --reload"
    depends_on:
      - db

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      - auth-service
      - data-storage-service
      - instrument-service
      - market-data-service
      - market-download-service

volumes:
  pgdata:

networks:
  dev-network:
    driver: bridge
